### ISSUE TITLE
Elaborate on the nature of the fork

### ISSUE THREAD

**Issue by Hyperseeker** [ChainsawGarden/Cataclysm-DDA-DF#1]
(I've decided to forgo the templates this one time, seeing how Discussions aren't set up for this repo yet and how this is neither a feature request nor a bug report. Apologies if this causes some chaos.)

Hi! I'm the developer of the Frontier Mods collection, which includes [Gunsmith](https://github.com/FrontierMods/Gunsmith) and [Armory](https://github.com/FrontierMods/Armory). (The former [has received praise from the player base](https://old.reddit.com/r/cataclysmdda/comments/pargs2/gunsmith_demo_gunmodding_overhaul/). The latter's unique features have been ultimately implemented on the engine level in the *DDA* proper.)

I've noticed that you keep developing this fork, which is exciting to me in no small part because of this fork's reimplementation of Lua: something I've been advocating for for a while. This kind of decentralized development, when it permits players to add their own functionality to the game without having to go through the gatekeepers, is something I'm a big fan of.

Partly, I'm also drawn to Delta Fork because of its promise to be "feature-complete" and "technologically-advanced". While these are both alluring promises, they don't exactly paint a clear picture as to the future of the fork.

I'd like to help any non-core *DDA* development if it aligns with my own goals. I have a suite of mods (shamefully, most are still in development) that seeks to expand the game significantly, which is something I could do on my own. However, if I could instead use my time to help someone implement something similar, I'm game.

If you could elaborate on what are you looking to achieve in more specific terms, that would be great. I'd like to lend a hand where I can. As I speak no C++, that would be JSON, docs, and the lore – the latter of which I have a good idea for.

— Steve

**Comment by ChainsawGarden** [comment]
Hello @Hyperseeker ! I apologize for the delay, I mostly just push code and check the Actions tab. I'll be more observant of GitHub from now on.

I greatly appreciate your work, and I would be humbled if you could implement your mod, Gunsmith, to be a permanent addition to Delta Fork. As there will be an arcade mode, players will be able to alternate between between "regular" guns to Gunsmith's more realistic gunmod system.

Now, let's get down to business. The following should give you more of an idea of what this fork is about.

# Concerning feature-completeness...
- When I think feature-complete, I think consistency in development. I don't want the players to have to figure out what the new controls are every nth release. Keybinds should be familiar and unchanging. Same concept can be applied to many other aspects of the game. Eating should make the player eat; if we were at a theoretical point earlier in time where eating would heal the player only, if I wanted Cataclysm to be arcade-y and not realistic, then there would be no point in making a whole hunger system in the base game. That could be a mod.

# Now, as for being a technologically-advanced fork:
## Lua
Lua's one of my biggest motivators into making this fork. As you've said yourself:
> This kind of decentralized development, when it permits players to add their own functionality to the game without having to go through the gatekeepers, is something I'm a big fan of.

Lua's very easy to use, great for rapid-prototyping, and is an overall great way to onramp new devs. As long as the C++ developers of the codebase is conscious of changes that could affect Lua users and devs, there should be no issue; especially with clear, consistent and concise communication.

I'm working on a couple of old Lua mods myself right now. Should be somewhere in my repos. And hopefully they inspire old lua modders to come back and add to the ecosystem. 

## AI Dynamicism
Heavily expanding on AI / NPCs and the dialogue system is in the works. 
- AI will (for the most part) make important decisions from its past experiences, mood, personality traits and beliefs attributes (that is completed concept-wise, will be implemented after the basic NPC Relationships release).
- Their traits and beliefs can change over time, either directly due to memory or from new experiences (and how they ultimately play out during a certain timeframe, which is typically until they go to sleep, but depending on the memory's weight, it may last for a week or so).
- Mood / morale will factor in (calculations wise) on what the AI will do. The more negative the morale, the higher the chance of something with a negative flavor occuring.
- Traits and beliefs will have the highest weight in how the AI will act. 
    - Let's tie this into DND's alignment mechanic. I'm not a DND player, but if I am correct, your alignment generally determines your actions. 
    - In Delta Fork terms, your "alignment" is equivalent to an individual personality trait or belief. "
    - In DND terms, Imagine if you had around 30 different "alignments". You are no longer just "Chaotic Evil". You have 30 different other alignments that determine how you act. One change in one could sway a decision in a myriad of ways.
- The player will be able to respond more naturally to NPCs-- though, the player will still be able to use dialogue options.
    - What I mean by this, is that there will be an assortment of words that the player will be able to say, and the player will be able to construct sentences with their appropriate contexts (For example, the context could be "Looting", and the player would be able to choose words suggesting that he or she wishes to loot a nearby book store in the town of Danville. The game will process the contexts only for the important parts (I <meaning "let's both"> want to **raid** **<bookstore>** in **Danville**). Any filler will just be to make it look pretty for the player.
- NPCs will react to player emotes. The player will be able to do things such as (but not limited to) `wave`, `point` at things, or flip the bird. NPCs will process what they've seen the player do, and create a memory profile of the player / other NPCs.
- NPCs will be able to seek shelter in buildings, and set up little homes inside them. "Scrap Tents" made out of cotton based products like shirts, pants, etc. are in the to-do and will be implemented soon. This will be a common sight on the outskirts of cities and other places that are relatively safe.
I'd say more, like how Dynamic Factions will tie in, but for the sake of putting my idea of "better AI" out there, I'll keep the list short.

## Multiplayer?
Multiplayer is confirmed but I won't be working on it until some time later. It's going to be split-screen for local players, and it'll have its own little servers people can set up over the internet. Splitscreen is going to be the most difficult, because apparently, windows doesn't like it when you connect multiple keyboards. But! I'll find a solution to that. I don't know where to start multiplayer-wise aside from setting up the sockets, so I put this on the backburner until I can't find anything else to work on.  

## Technical
On the technical side I want Delta Fork to be an easily-accessible ecosystem. I want people who want to start developing to understand how to code and how the game works. I'm working on my own instance of [moodle, an open-source learning platform](https://moodle.org/) to help on-ramp new modders & devs. No links yet, everything's being done offline.

I am working on mod tools and a launcher. Both will be made in Electron for the time being, then I'll play around with Tauri for saving performance.

## The Mod Market
One of my biggest projects for the future will be a mod market. Not a market where you can buy mods (because I don't believe in buying mods). But a decentralized, cryptographically secure market where you can request mods, make mods, and get paid for it. Think of it like a bounty system. Someone posts the mod idea, and specific parameters to narrow down on what needs to be made. Others can add to the request, thereby creating a "fund pool". Anyone can start working on the request. The entity/individual that satisfies all the requirements is paid by the fund pool.

To address the potential issue of having various developers submitting works that may far exceed quality and funder expectations of the "accepted" one, there will be options by the initial entity (whether it be a group or individual) to distribute funds to various mod developers, or the funders themselves will be able to vote on which modder to give the funds to. The works that did not receive funding would indeed remain on the market, tied to the original request. 
The software that facilitates this will be free, libre and open source just like the game itself.

I hope this wasn't too much to read, but this should give you a general idea of what I want to do with Delta Fork.

**Comment by Hyperseeker** [comment]
Is there a place where we can discuss all the ideas mentioned? Discord or, better yet, the Discussions page of this repo? I'm interested in further getting your response to the questions I have, as well as providing some ideas of my own.
